### ISSUE TITLE
회원 관리 기능 구현하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-hands-on-Spring-boot-3#1]
# 📌Feature Practice
>Security 프레임워크를 활용해 세션 방식으로 로그인 기능을 구현합니다.   

   

# 📝To-do
- [x] Security 관련 기본 설정
- [x] 로그인 기능 구현
- [x] 회원 가입 기능 구현
- [x] 중복 회원 검증 기능 구현
- [x] 세션 설정
- [x] 권한 설정
- [x] 사용자 정보 저장

   
# ✏️To-Study
- 스프링 시큐리티의 동작 과정을 공부합니다.
- 로그인, 회원 가입 로직을 구현합니다.
- 스프링에서 기본적으로 제공하는 UserDetails 클래스에 관해 공부합니다.
- 세션 설정에 관해 공부합니다.
- 계층 권한에 대해 공부합니다.
이후 JWT에 대해서도 공부할 예정입니다.
